### ISSUE TITLE
Forge client crashing after connecting to limbo

### ISSUE THREAD

**Issue by ToxiWoxi** [Nan1t/NanoLimbo#14]
When connecting to the limbo server using Forge, the game crashes.

Limbo Log:
```
[07:45:36] [INFO]: Starting server...
[07:45:37] [DEBUG]: Using Java NIO transport type
[07:45:37] [INFO]: Server started on localhost/127.0.0.1:30032
[07:45:40] [DEBUG]: Received packet PacketHandshake
[07:45:40] [DEBUG]: Pinged from /127.0.0.1:56501 [V1_18]
[07:45:40] [DEBUG]: Received packet PacketStatusRequest
[07:45:40] [DEBUG]: Sending PacketStatusResponse packet (153 bytes)
[07:45:40] [DEBUG]: Received packet PacketStatusPing
[07:45:40] [DEBUG]: Sending PacketStatusPing packet (9 bytes)
[07:45:46] [DEBUG]: Received packet PacketHandshake
[07:45:46] [DEBUG]: Pinged from /127.0.0.1:56505 [V1_18]
[07:45:46] [DEBUG]: Received packet PacketLoginStart
[07:45:46] [DEBUG]: Sending PacketLoginSuccess packet (27 bytes)
[07:45:46] [INFO]: Player ToxiWoxi connected (/127.0.0.1:56505)
[07:45:46] [DEBUG]: Sending PacketJoinGame packet (30940 bytes)
[07:45:46] [DEBUG]: Sending PacketPlayerAbilities packet (10 bytes)
[07:45:46] [DEBUG]: Sending PacketPlayerPositionAndLook packet (40 bytes)
[07:45:46] [DEBUG]: Sending PacketPlayerInfo packet (33 bytes)
[07:45:46] [DEBUG]: Sending PacketDeclareCommands packet (61 bytes)
[07:45:46] [DEBUG]: Sending PacketBossBar packet (59 bytes)
[07:45:46] [DEBUG]: Sending PacketChatMessage packet (55 bytes)
[07:45:46] [DEBUG]: Sending PacketTitleSetTitle packet (28 bytes)
[07:45:46] [DEBUG]: Sending PacketTitleSetSubTitle packet (26 bytes)
[07:45:46] [DEBUG]: Sending PacketTitleTimes packet (13 bytes)
[07:45:46] [DEBUG]: Sending PacketKeepAlive packet (9 bytes)
[07:45:46] [DEBUG]: Received packet PacketKeepAlive
[07:45:46] [WARNING]: Undefined incoming packet: 0xa
[07:45:46] [WARNING]: Undefined incoming packet: 0x5
[07:45:46] [WARNING]: Undefined incoming packet: 0xa
[07:45:46] [WARNING]: Undefined incoming packet: 0x0
[07:45:46] [WARNING]: Undefined incoming packet: 0x12
[07:45:47] [DEBUG]: Sending PacketKeepAlive packet (9 bytes)
[07:45:47] [DEBUG]: Received packet PacketKeepAlive
[07:45:49] [ERROR]: Unhandled exception:
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1134)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
[07:45:49] [INFO]: Player ToxiWoxi disconnected
```
Minecraft Crash Report:
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/24/22, 7:54 PM
Description: Unexpected error

java.lang.StackOverflowError: Unexpected error
	at com.mojang.brigadier.tree.RootCommandNode.<init>(RootCommandNode.java:20) ~[brigadier-1.0.18.jar%2336!/:?] {}
	at com.mojang.brigadier.builder.ArgumentBuilder.<init>(ArgumentBuilder.java:17) ~[brigadier-1.0.18.jar%2336!/:?] {}
	at com.mojang.brigadier.builder.RequiredArgumentBuilder.<init>(RequiredArgumentBuilder.java:16) ~[brigadier-1.0.18.jar%2336!/:?] {}
	at com.mojang.brigadier.builder.RequiredArgumentBuilder.argument(RequiredArgumentBuilder.java:22) ~[brigadier-1.0.18.jar%2336!/:?] {}
	at com.mojang.brigadier.tree.ArgumentCommandNode.createBuilder(ArgumentCommandNode.java:77) ~[brigadier-1.0.18.jar%2336!/:?] {}
	at com.mojang.brigadier.tree.ArgumentCommandNode.createBuilder(ArgumentCommandNode.java:23) ~[brigadier-1.0.18.jar%2336!/:?] {}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:149) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}

I shit you not, it literally says 
at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
a total of 1017 times here... 
I've deleted them so that I can fit this in the character limit of GitHub.


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.brigadier.tree.RootCommandNode.<init>(RootCommandNode.java:20) ~[brigadier-1.0.18.jar%2336!/:?] {}
	at com.mojang.brigadier.builder.ArgumentBuilder.<init>(ArgumentBuilder.java:17) ~[brigadier-1.0.18.jar%2336!/:?] {}
	at com.mojang.brigadier.builder.RequiredArgumentBuilder.<init>(RequiredArgumentBuilder.java:16) ~[brigadier-1.0.18.jar%2336!/:?] {}
	at com.mojang.brigadier.builder.RequiredArgumentBuilder.argument(RequiredArgumentBuilder.java:22) ~[brigadier-1.0.18.jar%2336!/:?] {}
	at com.mojang.brigadier.tree.ArgumentCommandNode.createBuilder(ArgumentCommandNode.java:77) ~[brigadier-1.0.18.jar%2336!/:?] {}
	at com.mojang.brigadier.tree.ArgumentCommandNode.createBuilder(ArgumentCommandNode.java:23) ~[brigadier-1.0.18.jar%2336!/:?] {}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:149) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}
	at net.minecraftforge.client.ClientCommandHandler.copy(ClientCommandHandler.java:151) ~[forge-1.18.1-39.0.59-universal.jar%2356!/:?] {re:classloading}

I shit you not, once again... this time, it says it a total of 1000 times.
  
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['NanoLimbo'/0, l='ClientLevel', x=0.00, y=64.00, z=0.00]]
	Chunk stats: 121, 0
	Level dimension: minecraft:world
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Server brand: ~~NULL~~
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.1-20211210.034407-srg.jar%2352!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2248) ~[client-1.18.1-20211210.034407-srg.jar%2352!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:682) ~[client-1.18.1-20211210.034407-srg.jar%2352!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2352!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.59.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 5708916752 bytes (5444 MiB) / 6442450944 bytes (6144 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 1660 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2182
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1123
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.60
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.60
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 39369.98
	Virtual memory used (MB): 22426.35
	Swap memory total (MB): 6656.00
	Swap memory used (MB): 0.00
	JVM Flags: 21 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -Xms6G -Xmn1G -XX:+DisableExplicitGC -XX:+UseNUMA -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
	Launched Version: 1.18.1-forge-39.0.59
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 511.23, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor 
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.18.1-39.0.59-universal.jar                |Forge                         |forge                         |39.0.59             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
	Crash Report UUID: c20e927f-b906-4231-ad8b-9c88f8b98fb3
	FML: 39.0
	Forge: net.minecraftforge:39.0.59
```

**Comment by Nan1t** [comment]
Do you use precompiled jar or compiled it yourself from main brabch?

**Comment by ToxiWoxi** [comment]
Precompiled.
This log was from 39.0.59, but I also tested 39.0.56, 39.0.46, 39.0.45, 39.0.44, 39.0.43, 39.0.40, 39.0.36, and 39.0.20

It appears that before 39.0.46, the client would not crash.

39.0.46 was when [Client Commands were added](https://github.com/MinecraftForge/MinecraftForge/commit/f1bafce27556f0b7b48d9f104d33a3caa81d578a), which helps explain why [ClientCommandHandler.java](https://github.com/MinecraftForge/MinecraftForge/blob/1.18.x/src/main/java/net/minecraftforge/client/ClientCommandHandler.java) had 1000+ errors.

**Comment by Nan1t** [comment]
Seems like this somehow fixed. I tested it with version built from main branch and there are no errors. Last released version still crashes Forge clients. I will release fix soon.

**Comment by Nan1t** [comment]
Check the new limbo version. It should be fixed.
